# Jekyll configuration
github_username: crazyzlj
name: Liang-Jun Zhu
title: Liang-Jun Zhu | 朱良君 | GISer, Watershed Modeler
description: Welcome to Liang-Jun Zhu's (朱良君) blog.


# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
port: 5000

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: fa fa-weibo fa-2x
    url: http://weibo.com/crazyzlj
  - class: fa fa-github fa-2x
    url: https://github.com/crazyzlj
  - class: fa fa-google fa-2x
    url: https://scholar.google.com/citations?user=FkNIpcQAAAAJ&hl=en
  - class: fa fa-facebook-official fa-2x
    url: https://www.facebook.com/liangjun.zhu.1
  - class: fa fa-twitter fa-2x
    url: https://twitter.com/LiangjunZhu

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-75301149-1'

# Set Comments
comments: true
# Deprecated disqus in 11/04/2017
disqus: 'liangjunzhusblog'
# use gitment, https://github.com/imsun/gitment
comment_gitment_repo: crazyzlj.github.io
comment_gitment_clientId: 596eb00067d481f2b930
comment_gitment_clientSecret: f34cf9bec7037758d1dfd313f7ed3455a01e262e

paginate: 6
paginate_path: "page:num"
excerpt_separator: "<!-- more -->"
syntax_highligher: rouge
markdown: kramdown
kramdown:
    auto_ids: true
    input: GFM
    syntax_highlighter: rouge

gems: ['jekyll-paginate','rouge']
timezone: Asia/Shanghai